name: Caller Workflow

on:
  workflow_dispatch:  # Allows manual triggering of this workflow

jobs:
  call-workflow2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Check out the repository

      - name: Call workflow2
        uses: actions/github-script@v6  # Use github-script action to call another workflow
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'workflow2.yml',  # Name of the workflow file to call
              ref: 'main',  # Branch or ref to trigger the workflow on
            });
