name: Echo Name

on:
  workflow_dispatch:
  
jobs:
  echo-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Echo Name
      run: echo "name:kranthi"
