name: test2

on:
  workflow_dispatch:

jobs:
  trigger_workflow2:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh

      - name: Trigger workflow2 with inputs
        run: |
          gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
          gh workflow run .github/workflows/workflow2.yml \
            --ref main \
            --field name="kranthi" \
            --field organization="accenture"
