name: Trigger Echo Name Workflow

on:
  workflow_dispatch:

jobs:
  trigger-echo-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Trigger the Echo Name Workflow
      uses: peter-evans/workflow-dispatch@v1
      with:
        repository: ${{ github.repository }}
        workflow: echo-name.yml
        ref: refs/heads/main
