name: Trigger workflow call

on:
  workflow_dispatch:  # Allow manual trigger for this workflow

jobs:
  trigger_deploy_vm:
    runs-on: ubuntu-latest

    steps:
      - name: Set up GitHub CLI
        uses: cli/cli-action@v2
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate the CLI

      - name: Trigger Workflow using gh CLI
        run: |
          gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
          gh workflow run workflow_call.yml --repo kranthi3149/accenture --ref main --json name="kranthi",organisation="accenture"
