name: Trigger workflow call

on:
  workflow_dispatch:

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the "workflow_call" workflow
        uses: ./.github/workflows/your-original-workflow.yml
        with:
          name: 'John Doe'
          organization: 'ExampleOrg'
