name: Trigger workflow call

on:
  workflow_dispatch:  # Allow manual trigger for this workflow

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow using cURL
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"ref":"main","inputs":{"name":"kranthi","organisation":"accenture"}}' \
            https://api.github.com/repos/kranthi3149/accenture/actions/workflows/workflow_call.yml/dispatches
