name: trigger-workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: write  # Allows triggering other workflows

jobs:
  call-workflow:
    uses: ./github/workflows/workflow_call.yml
    with:
      name: "kranthi"
      organization: "accenture"
