name: workflow2

on:
  workflow_call:
    inputs:
      name:
        description: 'Enter your name'
        required: true
        type: string
      organization:
        description: 'Enter your organization'
        required: false
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs
        run: |
          echo "Name: ${{ inputs.name }}"
          echo "Organization: ${{ inputs.organization }}"
