name: workflow2

on:
  workflow_dispatch:
     # inputs:
     #  name:
     #    description: 'Enter your name'
     #    required: true
     #    type: string
     #  organization:
     #    description: 'Enter your organization'
     #    required: true
     #    type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs
        run: |
          # echo "Name: ${{ github.event.inputs.name }}"
          # echo "Organization: ${{ github.event.inputs.organization }}"
          echo "kranthi"
