name: workflow2

on:
   workflow_call:
     inputs:
        name:
        description: 'Enter your name'
        required: true
        default: "reddy"
     
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Inputs
        run: |
          echo "Name: ${{ github.event.inputs.name }}"
          echo "Organization: ${{ github.event.inputs.organization }}"
         
